/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sms.program;

import java.awt.Checkbox;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListModel;


/**
 *
 * @author Admin
 */
public class EmpReg extends javax.swing.JFrame {
    
    int mousepX;
    int mousepY;
    public Connection conn1 = null;
    public Statement stmt1 = null;
    
    
    /**
     * Creates new form EmpReg
     */
    public EmpReg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel21 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel4.setMinimumSize(new java.awt.Dimension(744, 982));
        jPanel4.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(231, 231, 231));
        jPanel1.setMinimumSize(new java.awt.Dimension(744, 50));
        jPanel1.setNextFocusableComponent(jPanel1);
        jPanel1.setPreferredSize(new java.awt.Dimension(744, 50));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 39)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(170, 161, 82));
        jLabel8.setText("SMS Program");

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\SMS Program\\src\\sms\\program\\icons8_Close_Window_48px_2.png")); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\SMS Program\\src\\sms\\program\\icons8_Minimize_Window_48px_1.png")); // NOI18N
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel9))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1);
        jPanel1.setBounds(0, 0, 744, 50);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 0));
        jLabel4.setText("Last Name:");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(100, 370, 100, 22);
        jPanel4.add(jPasswordField2);
        jPasswordField2.setBounds(220, 800, 460, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 0));
        jLabel7.setText("Password:");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(110, 800, 90, 22);

        jTextField2.setToolTipText("");
        jPanel4.add(jTextField2);
        jTextField2.setBounds(220, 370, 460, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 0));
        jLabel5.setText("First Name:");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(100, 320, 110, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField1);
        jTextField1.setBounds(220, 320, 460, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 0));
        jLabel6.setText("Gender:");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(130, 420, 70, 22);
        jPanel4.add(jCalendar1);
        jCalendar1.setBounds(220, 470, 460, 155);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 153, 0));
        jLabel12.setText("Re-enter Password:");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(40, 860, 153, 22);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 153, 0));
        jLabel14.setText("Date of Birth:");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(90, 480, 110, 22);
        jPanel4.add(jPasswordField1);
        jPasswordField1.setBounds(220, 860, 460, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 0));
        jLabel13.setText("Occupation:");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(100, 650, 100, 22);
        jPanel4.add(jTextField3);
        jTextField3.setBounds(220, 650, 460, 30);
        jPanel4.add(jTextField4);
        jTextField4.setBounds(220, 700, 460, 30);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField5);
        jTextField5.setBounds(220, 750, 460, 30);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 153, 0));
        jLabel16.setText("E-mail:");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(140, 750, 60, 22);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 153, 0));
        jLabel15.setText("Phone Number:");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(70, 700, 123, 22);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Male", "Female" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(220, 410, 460, 50);

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\SMS Program\\src\\sms\\program\\Untitled.png")); // NOI18N
        jPanel4.add(jLabel21);
        jLabel21.setBounds(270, 0, 234, 230);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\SMS Program\\src\\sms\\program\\Registration_48px.png")); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(540, 910, 140, 60);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\SMS Program\\src\\sms\\program\\Broom_48px.png")); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(80, 910, 130, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 0));
        jLabel2.setText("Employee Registration");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(140, 220, 410, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 0));
        jLabel3.setText("Please fill in the required fields: ");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(210, 280, 253, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\SMS Program\\src\\sms\\program\\bg-samarew1.png")); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(-450, 0, 1530, 1440);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int Xcoordinate = evt.getXOnScreen();
        int Ycoordinate = evt.getYOnScreen();

        this.setLocation(Xcoordinate - mousepX, Ycoordinate - mousepY);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int k;
        // Text field shortcuts: ([1]: First Name, [2]: Last Name, [3]: Occupation, [4]: Phone Number, [5]: Email, [6]: Username)
        String txt1 = jTextField1.getText();
        String txt2 = jTextField2.getText();
        String txt3 = jTextField3.getText();
        String txt4 = jTextField4.getText();
        String txt5 = jTextField5.getText();
        String pwd1 = String.valueOf(jPasswordField1.getPassword());
        String pwd2 = String.valueOf(jPasswordField2.getPassword());
        String JP = "Admin";
        Connection conn = null;
        Connection conn1 = null;
        Connection conn2 = null;
        Connection conn3 = null;
        
        ListModel list = jList1.getModel();
        for(int i = 0; i < list.getSize(); i++)
        {
            Object obj = jList1.getModel().getElementAt(i);
        }
        
        // Formatting Date:
        SimpleDateFormat sysDate = new SimpleDateFormat("yyyy-MM-dd");
        String date_to_store = sysDate.format(jCalendar1.getDate());
        String lst = jList1.getName();
        java.util.Date dte = jCalendar1.getDate();

        // Error messages in case there are error inputting information:
        if (txt1.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Enter First Name");
        } else if (txt2.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Enter Last Name");
        } else if (txt3.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Enter Occupation/Position");
        } else if (txt4.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Enter Phone Number");
        } else if (txt5.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Enter E-mail");
        } else if(txt1.equals("") && txt2.equals("") && txt3.equals("") && txt4.equals("") && txt5.equals(""))
        {
            System.out.println("Fill the missing fields");
            JOptionPane.showMessageDialog(this,"Registeration Unsuccessful","Error",JOptionPane.ERROR_MESSAGE);
        } else
        {
            System.out.println("Registration Complete");
        }

        String txt3cck = txt3.toString();
        if(txt3cck.equals(JP))
        {
            try
            {
                Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
                System.out.println("Going to connect to employee database");
                conn2 = DriverManager.getConnection("jdbc:derby://localhost:1527/SMS Database;create=true");
                System.out.println("Connection Successfull");
                String sql2 = "INSERT INTO APP.EMPDB (EMAIL, PASSWORD, FIRSTNAME, LASTNAME, GENDER, DATEOFBIRTH, OCCUPATION, PHONENUMBER) values (?,?,?,?,?,?,?,?)";
                PreparedStatement st2 = conn2.prepareStatement(sql2);
                st2.setString(1, jTextField5.getText());
                System.out.println("Going to connect to employee database");
                st2.setString(2, String.valueOf(jPasswordField1.getPassword()));
                System.out.println("Going to connect to employee database");
                st2.setString(3, jTextField1.getText());
                System.out.println("Going to connect to employee database");
                st2.setString(4, jTextField2.getText());
                System.out.println("Going to connect to employee database");
                st2.setString(5, jList1.getSelectedValue());
                System.out.println("Going to connect to employee database");
                st2.setString(6, date_to_store);
                System.out.println("Going to connect to employee database");
                st2.setString(7, jTextField3.getText());
                System.out.println("Going to connect to employee database");
                st2.setString(8, jTextField4.getText());
                System.out.println("Going to connect to employee database");

                // Providing Confirmation message of completing the sign up:
                k = st2.executeUpdate();
                if (k > 0)
                {
                    JOptionPane.showMessageDialog(null, "Registeration Successfull");
                } else
                {
                    JOptionPane.showMessageDialog(null, "Registeration Unsuccessfull");
                }
            }catch(Exception e)
            {
                System.err.println("Got an exception for Employee reg!");
                System.err.println(e.getMessage());
            }
            // Closing the connection to database and closing the panel:
            finally
            {
                try {
                    conn2.close();
                } catch (SQLException ex)
                {
                    Logger.getLogger(AdminRec.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            try
            {
                Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
                System.out.println("Going to connect to database");
                conn = DriverManager.getConnection("jdbc:derby://localhost:1527/SMS Database;create=true");
                System.out.println("Connection Successfull");
                String sql = "INSERT INTO APP.ADMINDB (EMAIL, PASSWORD, FIRSTNAME, LASTNAME, JOBPOSITION) values (?,?,?,?,?)";
                PreparedStatement st = conn.prepareStatement(sql);
                
                st.setString(1, jTextField5.getText());
                st.setString(2, String.valueOf(jPasswordField1.getPassword()));
                st.setString(3, jTextField1.getText());
                st.setString(4, jTextField2.getText());
                st.setString(5, jTextField3.getText());
                
//                try{
//                    Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
//                    conn1 = DriverManager.getConnection("jdbc:derby://localhost:1527/SMS Database");
//                    System.out.println("Connection Successfull");
//                    Statement stmt= conn.createStatement();
//                    System.out.println("Accessing the database");
//                    ResultSet rs=stmt.executeQuery("SELECT EMP_ID FROM APP.EMPDB");
//                    if(rs.next())
//                    {
//                        String emp_ID = rs.getString("EMP_ID");
//                        st.setString(6, emp_ID);
//                    }
//                    }catch(Exception ex)
//                    {
//                System.err.println("Got an exception!");
//                System.err.println(ex.getMessage());
//                    }
//                finally{
//                    try {
//                    conn1.close();
//                    } catch (SQLException ex)
//                    {
//                    Logger.getLogger(AdminSignInPage.class.getName()).log(Level.SEVERE, null, ex);
//                    }
//                }
                // Providing Confirmation message of completing the sign up:
                k = st.executeUpdate();
                if (k > 0)
                {
                    JOptionPane.showMessageDialog(null, "Registeration Successfull");
                } else
                {
                    JOptionPane.showMessageDialog(null, "Registeration Unsuccessfull");
                }
            }catch(Exception e)
            {
                System.err.println("Got an exception for Admin reg!");
                System.err.println(e.getMessage());
            }
            // Closing the connection to database and closing the panel:
            finally
            {
                try {
                    conn.close();
                } catch (SQLException ex)
                {
                    Logger.getLogger(AdminRec.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else 
        {
            try
            {
                Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
                System.out.println("Going to connect to database");
                conn3 = DriverManager.getConnection("jdbc:derby://localhost:1527/SMS Database;create=true");
                System.out.println("Connection Successfull");
                String sql3 = "INSERT INTO APP.EMPDB (EMAIL, PASSWORD, FIRSTNAME, LASTNAME, GENDER, DATEOFBIRTH, OCCUPATION, PHONENUMBER) values (?,?,?,?,?,?,?,?)";
                PreparedStatement st3 = conn3.prepareStatement(sql3);
                st3.setString(1, jTextField5.getText());
                st3.setString(2, String.valueOf(jPasswordField1.getPassword()));
                st3.setString(3, jTextField1.getText());
                st3.setString(4, jTextField2.getText());
                st3.setString(5, jList1.getSelectedValue());
                st3.setString(6, date_to_store);
                st3.setString(7, jTextField3.getText());
                st3.setString(8, jTextField4.getText());

                // Providing Confirmation message of completing the sign up:
                st3.executeUpdate();
            }catch(Exception e)
            {
                System.err.println("Got an exception for Employee reg!");
                System.err.println(e.getMessage());
            }
            // Closing the connection to database and closing the panel:
            finally
            {
                try {
                    conn3.close();
                } catch (SQLException ex)
                {
                    Logger.getLogger(AdminRec.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        BulkSMSWelcome page = new BulkSMSWelcome();
        dispose();
        page.setVisible(true);
        page.getContentPane();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        //This button is used for clearing all the fields:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jPasswordField1.setText("");
        jPasswordField2.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int Xcoordinate = evt.getXOnScreen();
        int Ycoordinate = evt.getYOnScreen();

        this.setLocation(Xcoordinate - mousepX, Ycoordinate - mousepY);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        mousepX = evt.getX();
        mousepY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpReg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JCalendar jCalendar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
