/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sms.program.Panels;

// Importing packages:
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/**
 *
 * @author Admin
 */
public class SignUpPage extends javax.swing.JPanel {

    /**
     * Creates new form SignUpPage
     */
    public SignUpPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar1 = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jCalendar3 = new com.toedter.calendar.JCalendar();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1330, 710));
        setMinimumSize(new java.awt.Dimension(1330, 710));
        setPreferredSize(new java.awt.Dimension(1330, 710));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Attendee Information:");
        add(jLabel1);
        jLabel1.setBounds(490, 0, 269, 29);

        jLabel2.setText("Please input attendee information");
        add(jLabel2);
        jLabel2.setBounds(523, 36, 192, 16);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("First name:");
        add(jLabel3);
        jLabel3.setBounds(60, 70, 102, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Last name:");
        add(jLabel4);
        jLabel4.setBounds(60, 110, 100, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Gender:");
        add(jLabel5);
        jLabel5.setBounds(60, 140, 73, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Date of Birth:");
        add(jLabel6);
        jLabel6.setBounds(60, 200, 122, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Phone number:");
        add(jLabel7);
        jLabel7.setBounds(70, 500, 141, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Occupation:");
        add(jLabel8);
        jLabel8.setBounds(70, 540, 110, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("E-mail:");
        add(jLabel9);
        jLabel9.setBounds(80, 580, 64, 22);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\SMS Program\\src\\sms\\program\\Registration_48px.png")); // NOI18N
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(1180, 620, 140, 60);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\SMS Program\\src\\sms\\program\\Broom_48px.png")); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(680, 620, 130, 60);
        add(jTextField1);
        jTextField1.setBounds(220, 62, 1100, 30);
        add(jTextField2);
        jTextField2.setBounds(218, 101, 1100, 30);
        add(jTextField3);
        jTextField3.setBounds(218, 492, 1100, 30);
        add(jTextField4);
        jTextField4.setBounds(220, 532, 1100, 30);
        add(jTextField5);
        jTextField5.setBounds(220, 572, 1100, 30);

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Male", "Female" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        add(jScrollPane2);
        jScrollPane2.setBounds(218, 142, 1100, 54);
        add(jCalendar3);
        jCalendar3.setBounds(218, 203, 1100, 283);
        add(jLabel10);
        jLabel10.setBounds(483, 48, 0, 0);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Documents\\NetBeansProjects\\SMS Program\\src\\sms\\program\\bg-samarew1.png")); // NOI18N
        add(jLabel11);
        jLabel11.setBounds(0, 0, 1330, 1440);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                // Formatting list:
        ListModel list = jList1.getModel();
        for(int i = 0; i < list.getSize(); i++)
        {
            Object obj = jList1.getModel().getElementAt(i);
        }
        
        // Formatting Date:
        SimpleDateFormat sysDate = new SimpleDateFormat("yyyy-MM-dd");
        String date_to_store = sysDate.format(jCalendar3.getDate());
        
        String txt1 = jTextField1.getText();
        String txt2 = jTextField2.getText();
        String txt3 = jTextField3.getText();
        String txt4 = jTextField4.getText();
        String txt5 = jTextField5.getText(); 
        String lst = jList1.getName();
        java.util.Date dte = jCalendar3.getDate();

        Connection conn = null;
        
        
        // Error messages in case there are error inputting information:
        if (txt1.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Enter First Name");
        } else if (txt2.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Enter Last Name");
        } else if (txt3.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Enter Phone number");
        } else if (txt4.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Enter Occupation");
        } else if (txt5.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Enter E-mail");
        } else if(txt1.equals("") && txt2.equals("") && txt3.equals("") && txt4.equals("") && txt5.equals(""))
        {
            System.out.println("Fill the missing fields");
            JOptionPane.showMessageDialog(this,"Registeration Unsuccessful","Error",JOptionPane.ERROR_MESSAGE);
        } else
        {
            System.out.println("Registration Complete");
        }
        
        // Establishing a connection with database and store information in the database:
        try
        {
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
        System.out.println("Going to connect to database");
        conn = DriverManager.getConnection("jdbc:derby://localhost:1527/SMS Database;create=true");
        System.out.println("Connection Successfull");
        String sql = "INSERT INTO APP.ATENDB (FIRSTNAME, LASTNAME, GENDER, DATEOFBIRTH, PHONENUMBER, OCCUPATION, EMAIL) values (?,?,?,?,?,?,?)";
        PreparedStatement st = conn.prepareStatement(sql);
        st.setString(1, jTextField1.getText());
        st.setString(2, jTextField2.getText());
        st.setString(3, jList1.getSelectedValue());
        st.setString(4, date_to_store);
        st.setString(5, jTextField3.getText());
        st.setString(6, jTextField4.getText());
        st.setString(7, jTextField5.getText());
          
        // Providing Confirmation message of completing the sign up:
        int i = st.executeUpdate();
        if (i > 0)
        {
            JOptionPane.showMessageDialog(null, "Registeration Successfull");
        } else
        {
            JOptionPane.showMessageDialog(null, "Registeration Unsuccessfull");
        }
        } catch(Exception e){
            System.err.println("Got an exception!");
            System.err.println(e.getMessage());
        }
        
        // Closing the connection to database and closing the panel:
        finally
        {
            try {
                conn.close();
            } catch (SQLException ex)
            {
                Logger.getLogger(SignUpPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        //This button is used for clearing all the fields:
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText(""); 
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JCalendar jCalendar1;
    private com.toedter.calendar.JCalendar jCalendar3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
